feat: added tasks part1
SovanMarat/JS-Front-end-Lab pull request #22
Opened 2021-05-27 19:45 UTC by SovanMarat

added solution for 10 tasks

2021-05-29 21:34 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +]);
если использовать подобные данный, вроде как все ок, задача выполняется:
`
let exp1 = [1, 0, 2, 3]; 
let exp2 = [90000, 15, 100, 45, 99, 13, 2];
let exp3 = [-500, 0, 50];
--->
console.info(exp1); //  { index: 1,  value: 0} 
console.info(exp2); // { index: 6,  value: 2} 
console.info(exp3); //  { index: 0,  value: -500} 
Тут все верно!!!
----
Но если немного изменились входные данные, то функция окажится не универсальной
типа:
let exp4 = [];
let res = getMinItemParam(exp4) 

console.info(exp4 ); //  { index: 0,  value: undefined} 


`

2021-05-30 16:50 UTC, DimaKacer approved these changes

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +};
второй момент, т.к. задачи сугубо для практики, хотел бы попросить уделять внимание и дефолтным проверкам аргументов функции, чтобы отрабатывать негативные сценарии функционала

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +  return Array.from(unique);
Приветствую изучения новых фич, но хотел бы попросить еще сделать и альтернативное решение, с более легким подходом

- сделать так, чтобы данная функция (в том же составе фич, которые уже используются в теле этой функции) заработала и в браузере IE11, пока он еще жив))

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.groupEnd("#14 Operator");
- [x]  Verified

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +]);
- [x]  Verified

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#16 test uniqueValues", [uniqueValues([3, 1, 3, 5, 2, 4, 4, 4])]);
- [x]  Verified

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#17 test persons", adminAr(persons));
- попробуй написать нужную функцию, с использованием методов мвссива, которые уже возвращают массив, так будет рациональнее
- проверь входные аргументы, чтобы они были валидными, для выполнения дальнейших операций/условий в теле функции
- имя функции ничего "не говорит" за что она отвечает

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#18 test funFlat", funFlat(nested));
Добавь плиз еще как минимум два альтернативных способа, для решения этой задачи

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#17 test persons", adminAr(persons));
- [x]  Verified

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#18 test funFlat", funFlat(nested));
- [x]  Verified

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#19 test getIntersection", getIntersection(arr1, arr2));
Вижу что с такими фичами как forEach и Set оч хорошо дружишь)
Добавь плиз альтернативное решение данной задачи, без forEach и Set, это поможет погрузиться в глубь JS  и работы с массивами. спасибо

2021-05-30 16:50 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#19 test getIntersection", getIntersection(arr1, arr2));
В настоящее время, все меньше и меньше нужно заботиться об кросбраузерности, чаще всего это делают вспомогательные инструменты/либы/полифилы, но нужно обращаться к таким источникам, чтобы убедиться, будет ли работать написанный код и на других браузерах/платформах.. 

для доп инфы о чем речь, смотри ниже и ссылки (нужно уметь читать инфу с подобных источников)

![image](https://user-images.githubusercontent.com/10163185/120112693-80275200-c17f-11eb-8513-972565e75ce7.png)

https://caniuse.com/?search=array%20set

https://kangax.github.io/compat-table/es6/#test-proper_tail_calls_(tail_call_optimisation)

2021-05-30 20:14 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#19 test getIntersection", getIntersection(arr1, arr2));
Дополнительная задача - нужно разобрать:

Чему равен typeof null в режиме use strict?

2021-05-31 18:40 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks.js
> +console.log(typeof new String("hello")); // "object"
При использовании конструктора String (Number, boolean) происходит так называемое явное создание **объекта**-обёртки. Это не рекомендуется делать в JS.

2021-05-31 19:38 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks.js
> +console.info("#19 test getIntersection", getIntersection(arr1, arr2));
typeof null в режиме use strict равен **object** (как и без use strict)
Это признаный баг JS.

2021-05-31 20:41 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks.js
> +console.log(typeof new Boolean(true)); // "object"
true, false, boolean. 
На мой взгляд ожидаемые результаты.

2021-05-31 20:43 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks.js
> +console.log(typeof false); // "boolean"
Boolean, неожиданно. Понять тяжело))

2021-05-31 20:46 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks.js
> +console.log(typeof function () {}); // "function"
Object. Но js выделяет его в подвид объектов function, для нашего удобства.

2021-06-02 22:21 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +console.info("#17 test persons", findAdminAr(persons));
Смотри, твой вариант результата 
![image](https://user-images.githubusercontent.com/10163185/120557633-e671d600-c406-11eb-8afc-b79d6fded6b8.png)

а вот мой вариант ) ты был крайне близок)

const findAdminAr = (arr) => [...arr]?.find((item) => item.group === "admin" && item.name.includes("ar")) || {};

![image](https://user-images.githubusercontent.com/10163185/120558049-8d567200-c407-11eb-81de-c86a6bec466b.png)

* В моем варианте, даже если в аргументы попадет не массив, а например строка, то и это не беда))

2021-06-02 22:21 UTC, DimaKacer commented on pdp/TASKS_PART1/tasks.js
> +
на самом деле, круть!

но вот еще один, без особого полета фантазий)

  const funFlat4 = (arr) => arr.reduce((acc, item) => [...acc, ...item], []);

2021-06-03 12:38 UTC, DimaKacer requested changes

2021-06-04 19:55 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks.js
> +console.info("#17 test persons", findAdminAr(persons));
Согласен, в своем варианте меняю filter на find))

2021-06-04 20:06 UTC, SovanMarat commented on pdp/TASKS_PART1/tasks23.js
> +console.log("polindrom", polindrom("ab c c ba"));
`const polindrom = (str) => {
  if (typeof str === "string") {
    return (str.toLowerCase() === str.toLowerCase().split("").reverse().join("")) ? true : false;
  }
   else {
    return false;
  }
};
console.log("polindrom", polindrom("ab c c ba"));`

2021-06-16 21:17 UTC, merged